import { Player, Vote } from "../types.ts";

export class InMemoryVoteRepository {
  votes: Vote[] = [];

  constructor(private readonly initialVotes: Vote[] = []) {
    this.votes = [...initialVotes];
  }

  getLastVote(email: string): Promise<Vote | undefined> {
    const sortedVotes = this.votes
      .filter((_) => _.email === email)
      .sort((a, b) => b.votedDate.getTime() - a.votedDate.getTime());

    return Promise.resolve(sortedVotes[0]);
  }

  getVotes(email: string): Vote[] {
    return this.votes.filter((_) => _.email === email);
  }

  saveVote(vote: Vote): Promise<void> {
    this.votes.push(vote);
    return Promise.resolve();
  }
}

export class InMemoryPlayersRepository {
  players: Player[] = [];

  constructor(private readonly initialPlayers: Player[] = []) {
    this.players = [...initialPlayers];
  }

  listPlayersById(playerIds: number[]): Promise<Player[]> {
    const players = this.players.filter((_) => playerIds.includes(_.id));
    return Promise.resolve(players);
  }

  updatePlayersVoteCount(playerIds: number[]): Promise<void> {
    const newPlayers = this.players.map((p) => {
      if (playerIds.includes(p.id)) {
        return {
          ...p,
          votes: p.votes + 1,
        };
      } else {
        return p;
      }
    });
    this.players = [...newPlayers];
    return Promise.resolve();
  }
}

export const players: Player[] = [
  {
    id: 617,
    personalInfo: {
      name: "Ederson Moraes",
      firstname: "Ederson",
      lastname: "Santana de Moraes",
      age: 28,
      nationality: "Brazil",
      height: "188 cm",
      weight: "86 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/617.png",
    },
    statistics: [
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 32,
          lineups: 32,
          minutes: 2880,
          number: null,
          position: "Goalkeeper",
          rating: "6.896875",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 23, assists: 1, saves: 53 },
        passes: { total: 848, key: 1, accuracy: 21 },
        tackles: { total: 2, blocks: null, interceptions: null },
        duels: { total: 14, won: 11 },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: 4, committed: 1 },
        cards: { yellow: 3, yellowred: 0, red: 0 },
        penalty: { won: null, commited: null, scored: 0, missed: 0, saved: 0 },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: "Goalkeeper",
          rating: null,
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 3 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 0, assists: null, saves: null },
        passes: { total: null, key: null, accuracy: null },
        tackles: { total: null, blocks: null, interceptions: null },
        duels: { total: null, won: null },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: null, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: { won: null, commited: null, scored: 0, missed: 0, saved: 0 },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: "Goalkeeper",
          rating: null,
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 5 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 0, assists: null, saves: null },
        passes: { total: null, key: null, accuracy: null },
        tackles: { total: null, blocks: null, interceptions: null },
        duels: { total: null, won: null },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: null, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: { won: null, commited: null, scored: 0, missed: 0, saved: 0 },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 10,
          lineups: 10,
          minutes: 900,
          number: null,
          position: "Goalkeeper",
          rating: "6.980000",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 4, assists: null, saves: 16 },
        passes: { total: 239, key: null, accuracy: 20 },
        tackles: { total: null, blocks: null, interceptions: null },
        duels: { total: 4, won: 4 },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: 2, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: { won: null, commited: null, scored: 0, missed: 0, saved: 0 },
      },
    ],
    total: {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 42,
        lineups: 42,
        minutes: 3780,
        number: null,
        position: "Goalkeeper",
        rating: "5.342763671875",
        captain: false,
      },
      substitutes: { in: 0, out: 0, bench: 8 },
      shots: { total: null, on: null },
      goals: { total: 0, conceded: 27, assists: 1, saves: 69 },
      passes: { total: 1087, key: 1, accuracy: 41 },
      tackles: { total: 2, blocks: null, interceptions: null },
      duels: { total: 18, won: 15 },
      dribbles: { attempts: null, success: null, past: null },
      fouls: { drawn: 6, committed: 1 },
      cards: { yellow: 3, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 0, missed: 0, saved: 0 },
    },
    votes: 0,
  },
  {
    id: 127,
    personalInfo: {
      name: "M. ter Stegen",
      firstname: "Marc-André",
      lastname: "ter Stegen",
      age: 29,
      nationality: "Germany",
      height: "187 cm",
      weight: "85 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/127.png",
    },
    statistics: [
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 140,
          name: "Primera Division",
          country: "Spain",
          logo: "https://media.api-sports.io/football/leagues/140.png",
          flag: "https://media.api-sports.io/flags/es.svg",
          season: 2020,
        },
        games: {
          appearences: 26,
          lineups: 26,
          minutes: 2340,
          number: null,
          position: "Goalkeeper",
          rating: "6.903846",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: 1, on: null },
        goals: { total: 0, conceded: 23, assists: null, saves: 65 },
        passes: { total: 770, key: 1, accuracy: 25 },
        tackles: { total: null, blocks: null, interceptions: null },
        duels: { total: 8, won: 5 },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: null, committed: 1 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: { won: null, commited: null, scored: 0, missed: 0, saved: 0 },
      },
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 143,
          name: "Copa del Rey",
          country: "Spain",
          logo: "https://media.api-sports.io/football/leagues/143.png",
          flag: "https://media.api-sports.io/flags/es.svg",
          season: 2020,
        },
        games: {
          appearences: 4,
          lineups: 4,
          minutes: 420,
          number: null,
          position: "Goalkeeper",
          rating: "6.875000",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 2 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 5, assists: null, saves: 6 },
        passes: { total: 135, key: null, accuracy: 28 },
        tackles: { total: null, blocks: null, interceptions: null },
        duels: { total: 2, won: 1 },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: null, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: { won: null, commited: null, scored: 0, missed: 0, saved: 3 },
      },
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 5,
          lineups: 5,
          minutes: 450,
          number: null,
          position: "Goalkeeper",
          rating: "6.820000",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 9, assists: null, saves: 16 },
        passes: { total: 112, key: null, accuracy: 20 },
        tackles: { total: null, blocks: null, interceptions: null },
        duels: { total: 2, won: 2 },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: null, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: { won: null, commited: null, scored: 0, missed: 0, saved: 1 },
      },
    ],
    total: {
      team: {
        id: 529,
        name: "Barcelona",
        logo: "https://media.api-sports.io/football/teams/529.png",
      },
      league: {
        id: 140,
        name: "Primera Division",
        country: "Spain",
        logo: "https://media.api-sports.io/football/leagues/140.png",
        flag: "https://media.api-sports.io/flags/es.svg",
        season: 2020,
      },
      games: {
        appearences: 35,
        lineups: 35,
        minutes: 3210,
        number: null,
        position: "Goalkeeper",
        rating: "1.70888821875",
        captain: false,
      },
      substitutes: { in: 0, out: 0, bench: 2 },
      shots: { total: 1, on: null },
      goals: { total: 0, conceded: 37, assists: null, saves: 87 },
      passes: { total: 1017, key: 1, accuracy: 73 },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: 12, won: 8 },
      dribbles: { attempts: null, success: null, past: null },
      fouls: { drawn: null, committed: 1 },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: null,
        missed: null,
        saved: 4,
      },
    },
    votes: 0,
  },
  {
    id: 629,
    personalInfo: {
      name: "K. De Bruyne",
      firstname: "Kevin",
      lastname: "De Bruyne",
      age: 30,
      nationality: "Belgium",
      height: "181 cm",
      weight: "68 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/629.png",
    },
    statistics: [
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 24,
          lineups: 22,
          minutes: 1911,
          number: null,
          position: "Midfielder",
          rating: "7.725000",
          captain: false,
        },
        substitutes: { in: 2, out: 6, bench: 4 },
        shots: { total: 51, on: 25 },
        goals: { total: 5, conceded: 0, assists: 11, saves: null },
        passes: { total: 1205, key: 74, accuracy: 41 },
        tackles: { total: 34, blocks: 1, interceptions: 9 },
        duels: { total: 223, won: 110 },
        dribbles: { attempts: 61, success: 42, past: null },
        fouls: { drawn: 30, committed: 24 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 2,
          missed: 1,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 4,
          lineups: 3,
          minutes: 270,
          number: null,
          position: "Midfielder",
          rating: "7.350000",
          captain: false,
        },
        substitutes: { in: 1, out: 2, bench: 1 },
        shots: { total: 1, on: null },
        goals: { total: 0, conceded: 0, assists: 1, saves: null },
        passes: { total: 168, key: 10, accuracy: 33 },
        tackles: { total: 3, blocks: null, interceptions: null },
        duels: { total: 26, won: 14 },
        dribbles: { attempts: 6, success: 5, past: null },
        fouls: { drawn: 4, committed: 3 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 2,
          minutes: 104,
          number: null,
          position: "Midfielder",
          rating: "7.400000",
          captain: false,
        },
        substitutes: { in: 1, out: 2, bench: 1 },
        shots: { total: 1, on: 1 },
        goals: { total: 1, conceded: 0, assists: 1, saves: null },
        passes: { total: 60, key: 8, accuracy: 15 },
        tackles: { total: 3, blocks: null, interceptions: 1 },
        duels: { total: 11, won: 6 },
        dribbles: { attempts: 3, success: 1, past: null },
        fouls: { drawn: 1, committed: 2 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 6,
          lineups: 6,
          minutes: 527,
          number: null,
          position: "Midfielder",
          rating: "8.000000",
          captain: false,
        },
        substitutes: { in: 0, out: 2, bench: 3 },
        shots: { total: 13, on: 7 },
        goals: { total: 3, conceded: 0, assists: 4, saves: null },
        passes: { total: 363, key: 14, accuracy: 52 },
        tackles: { total: 7, blocks: 2, interceptions: 1 },
        duels: { total: 58, won: 26 },
        dribbles: { attempts: 16, success: 10, past: null },
        fouls: { drawn: 7, committed: 7 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 37,
        lineups: 33,
        minutes: 2812,
        number: null,
        position: "Midfielder",
        rating: "7.852734375",
        captain: false,
      },
      substitutes: { in: 4, out: 12, bench: 9 },
      shots: { total: 66, on: 33 },
      goals: { total: 9, conceded: 0, assists: 17, saves: null },
      passes: { total: 1796, key: 106, accuracy: 141 },
      tackles: { total: 47, blocks: 3, interceptions: 11 },
      duels: { total: 318, won: 156 },
      dribbles: { attempts: 86, success: 58, past: null },
      fouls: { drawn: 42, committed: 36 },
      cards: { yellow: 2, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 2, missed: 1, saved: null },
    },
    votes: 0,
  },
  {
    id: 633,
    personalInfo: {
      name: "İ. Gündoğan",
      firstname: "İlkay",
      lastname: "Gündoğan",
      age: 31,
      nationality: "Germany",
      height: "180 cm",
      weight: "80 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/633.png",
    },
    statistics: [
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 25,
          lineups: 21,
          minutes: 1866,
          number: null,
          position: "Midfielder",
          rating: "7.320000",
          captain: false,
        },
        substitutes: { in: 4, out: 6, bench: 8 },
        shots: { total: 37, on: 20 },
        goals: { total: 12, conceded: 0, assists: 1, saves: null },
        passes: { total: 1546, key: 37, accuracy: 56 },
        tackles: { total: 19, blocks: 3, interceptions: 19 },
        duels: { total: 139, won: 73 },
        dribbles: { attempts: 34, success: 24, past: null },
        fouls: { drawn: 21, committed: 6 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 1,
          missed: 1,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 2,
          lineups: 2,
          minutes: 180,
          number: null,
          position: "Midfielder",
          rating: "7.000000",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 1 },
        shots: { total: 2, on: null },
        goals: { total: 0, conceded: 0, assists: null, saves: null },
        passes: { total: 141, key: 5, accuracy: 63 },
        tackles: { total: 1, blocks: null, interceptions: 4 },
        duels: { total: 15, won: 7 },
        dribbles: { attempts: 2, success: null, past: null },
        fouls: { drawn: 3, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 4,
          lineups: 2,
          minutes: 195,
          number: null,
          position: "Midfielder",
          rating: "7.250000",
          captain: false,
        },
        substitutes: { in: 2, out: 2, bench: 3 },
        shots: { total: 1, on: 1 },
        goals: { total: 1, conceded: 0, assists: 1, saves: null },
        passes: { total: 130, key: 5, accuracy: 29 },
        tackles: { total: 3, blocks: 1, interceptions: 1 },
        duels: { total: 9, won: 6 },
        dribbles: { attempts: 3, success: 1, past: null },
        fouls: { drawn: 2, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 10,
          lineups: 10,
          minutes: 798,
          number: null,
          position: "Midfielder",
          rating: "7.260000",
          captain: false,
        },
        substitutes: { in: 0, out: 5, bench: 1 },
        shots: { total: 8, on: 4 },
        goals: { total: 3, conceded: 0, assists: 1, saves: null },
        passes: { total: 775, key: 9, accuracy: 71 },
        tackles: { total: 13, blocks: null, interceptions: 11 },
        duels: { total: 73, won: 37 },
        dribbles: { attempts: 16, success: 12, past: null },
        fouls: { drawn: 8, committed: 12 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 41,
        lineups: 35,
        minutes: 3039,
        number: null,
        position: "Midfielder",
        rating: "7.246874999999999",
        captain: false,
      },
      substitutes: { in: 6, out: 13, bench: 13 },
      shots: { total: 48, on: 25 },
      goals: { total: 16, conceded: 0, assists: 3, saves: null },
      passes: { total: 2592, key: 56, accuracy: 219 },
      tackles: { total: 36, blocks: 4, interceptions: 35 },
      duels: { total: 236, won: 123 },
      dribbles: { attempts: 55, success: 37, past: null },
      fouls: { drawn: 34, committed: 18 },
      cards: { yellow: 2, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 1, missed: 1, saved: null },
    },
    votes: 0,
  },
  {
    id: 636,
    personalInfo: {
      name: "Bernardo Silva",
      firstname: "Bernardo",
      lastname: "Mota Veiga de Carvalho e Silva",
      age: 27,
      nationality: "Portugal",
      height: "173 cm",
      weight: "64 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/636.png",
    },
    statistics: [
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 24,
          lineups: 22,
          minutes: 1904,
          number: null,
          position: "Midfielder",
          rating: "7.029166",
          captain: false,
        },
        substitutes: { in: 2, out: 6, bench: 9 },
        shots: { total: 22, on: 13 },
        goals: { total: 2, conceded: 0, assists: 6, saves: null },
        passes: { total: 1273, key: 25, accuracy: 48 },
        tackles: { total: 25, blocks: 1, interceptions: 15 },
        duels: { total: 220, won: 93 },
        dribbles: { attempts: 61, success: 39, past: null },
        fouls: { drawn: 18, committed: 16 },
        cards: { yellow: 4, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 3,
          minutes: 220,
          number: null,
          position: "Midfielder",
          rating: "7.633333",
          captain: false,
        },
        substitutes: { in: 0, out: 2, bench: 2 },
        shots: { total: 6, on: 3 },
        goals: { total: 2, conceded: 0, assists: 1, saves: null },
        passes: { total: 154, key: 3, accuracy: 47 },
        tackles: { total: 1, blocks: null, interceptions: null },
        duels: { total: 9, won: 4 },
        dribbles: { attempts: 2, success: 1, past: null },
        fouls: { drawn: 1, committed: 1 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 1,
          minutes: 99,
          number: null,
          position: "Midfielder",
          rating: "6.700000",
          captain: false,
        },
        substitutes: { in: 2, out: 1, bench: 2 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 0, assists: null, saves: null },
        passes: { total: 57, key: 1, accuracy: 16 },
        tackles: { total: 2, blocks: null, interceptions: 1 },
        duels: { total: 11, won: 6 },
        dribbles: { attempts: 3, success: 1, past: null },
        fouls: { drawn: 3, committed: 1 },
        cards: { yellow: 2, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 11,
          lineups: 9,
          minutes: 784,
          number: null,
          position: "Midfielder",
          rating: "6.909090",
          captain: false,
        },
        substitutes: { in: 2, out: 2, bench: 2 },
        shots: { total: 8, on: 5 },
        goals: { total: 1, conceded: 0, assists: 2, saves: null },
        passes: { total: 456, key: 14, accuracy: 36 },
        tackles: { total: 11, blocks: null, interceptions: 3 },
        duels: { total: 72, won: 31 },
        dribbles: { attempts: 25, success: 11, past: null },
        fouls: { drawn: 6, committed: 8 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 41,
        lineups: 35,
        minutes: 3007,
        number: null,
        position: "Midfielder",
        rating: "6.905710703125",
        captain: false,
      },
      substitutes: { in: 6, out: 11, bench: 15 },
      shots: { total: 36, on: 21 },
      goals: { total: 5, conceded: 0, assists: 9, saves: null },
      passes: { total: 1940, key: 43, accuracy: 147 },
      tackles: { total: 39, blocks: 1, interceptions: 19 },
      duels: { total: 312, won: 134 },
      dribbles: { attempts: 91, success: 52, past: null },
      fouls: { drawn: 28, committed: 26 },
      cards: { yellow: 7, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 0, missed: 0, saved: null },
    },
    votes: 0,
  },
  {
    id: 855,
    personalInfo: {
      name: "João Cancelo",
      firstname: "João Pedro",
      lastname: "Cavaco Cancelo",
      age: 27,
      nationality: "Portugal",
      height: "182 cm",
      weight: "74 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/855.png",
    },
    statistics: [
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 24,
          lineups: 23,
          minutes: 2038,
          number: null,
          position: "Defender",
          rating: "7.283333",
          captain: false,
        },
        substitutes: { in: 1, out: 2, bench: 7 },
        shots: { total: 20, on: 9 },
        goals: { total: 1, conceded: 0, assists: 3, saves: null },
        passes: { total: 1631, key: 43, accuracy: 58 },
        tackles: { total: 58, blocks: 2, interceptions: 35 },
        duels: { total: 277, won: 140 },
        dribbles: { attempts: 74, success: 43, past: null },
        fouls: { drawn: 11, committed: 33 },
        cards: { yellow: 4, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 3,
          minutes: 270,
          number: null,
          position: "Defender",
          rating: "7.466666",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: 2, on: 1 },
        goals: { total: 0, conceded: 0, assists: null, saves: null },
        passes: { total: 211, key: 6, accuracy: 56 },
        tackles: { total: 7, blocks: null, interceptions: 7 },
        duels: { total: 47, won: 29 },
        dribbles: { attempts: 8, success: 7, past: null },
        fouls: { drawn: 2, committed: 6 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 2,
          minutes: 149,
          number: null,
          position: "Defender",
          rating: "7.133333",
          captain: false,
        },
        substitutes: { in: 1, out: 1, bench: 3 },
        shots: { total: 1, on: null },
        goals: { total: 0, conceded: 0, assists: 1, saves: null },
        passes: { total: 137, key: 3, accuracy: 37 },
        tackles: { total: 5, blocks: 1, interceptions: 1 },
        duels: { total: 19, won: 9 },
        dribbles: { attempts: 7, success: 3, past: null },
        fouls: { drawn: null, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "https://media.api-sports.io/football/teams/50.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 9,
          lineups: 7,
          minutes: 605,
          number: null,
          position: "Defender",
          rating: "7.188888",
          captain: false,
        },
        substitutes: { in: 2, out: 2, bench: 4 },
        shots: { total: 7, on: 3 },
        goals: { total: 1, conceded: 0, assists: 1, saves: null },
        passes: { total: 549, key: 8, accuracy: 53 },
        tackles: { total: 24, blocks: null, interceptions: 6 },
        duels: { total: 98, won: 55 },
        dribbles: { attempts: 31, success: 17, past: null },
        fouls: { drawn: 2, committed: 11 },
        cards: { yellow: 3, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 39,
        lineups: 35,
        minutes: 3062,
        number: null,
        position: "Defender",
        rating: "7.1929679843750005",
        captain: false,
      },
      substitutes: { in: 4, out: 5, bench: 14 },
      shots: { total: 30, on: 13 },
      goals: { total: 2, conceded: 0, assists: 5, saves: null },
      passes: { total: 2528, key: 60, accuracy: 204 },
      tackles: { total: 94, blocks: 3, interceptions: 49 },
      duels: { total: 441, won: 233 },
      dribbles: { attempts: 120, success: 70, past: null },
      fouls: { drawn: 15, committed: 50 },
      cards: { yellow: 8, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 0, missed: 0, saved: null },
    },
    votes: 0,
  },
  {
    id: 904,
    personalInfo: {
      name: "P. Pogba",
      firstname: "Paul",
      lastname: "Pogba",
      age: 28,
      nationality: "France",
      height: "191 cm",
      weight: "84 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/904.png",
    },
    statistics: [
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 23,
          lineups: 18,
          minutes: 1626,
          number: null,
          position: "Midfielder",
          rating: "7.026086",
          captain: false,
        },
        substitutes: { in: 5, out: 4, bench: 7 },
        shots: { total: 20, on: 11 },
        goals: { total: 3, conceded: 0, assists: 3, saves: null },
        passes: { total: 1186, key: 19, accuracy: 43 },
        tackles: { total: 31, blocks: 1, interceptions: 23 },
        duels: { total: 290, won: 155 },
        dribbles: { attempts: 56, success: 41, past: null },
        fouls: { drawn: 35, committed: 33 },
        cards: { yellow: 3, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 2,
          lineups: 2,
          minutes: 154,
          number: null,
          position: "Midfielder",
          rating: "6.900000",
          captain: false,
        },
        substitutes: { in: 0, out: 1, bench: 0 },
        shots: { total: 5, on: 1 },
        goals: { total: 0, conceded: 0, assists: null, saves: null },
        passes: { total: 78, key: null, accuracy: 33 },
        tackles: { total: 1, blocks: 2, interceptions: 3 },
        duels: { total: 14, won: 5 },
        dribbles: { attempts: 2, success: 1, past: null },
        fouls: { drawn: 1, committed: 1 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 2,
          minutes: 201,
          number: null,
          position: "Midfielder",
          rating: "7.100000",
          captain: false,
        },
        substitutes: { in: 1, out: 0, bench: 1 },
        shots: { total: 3, on: 2 },
        goals: { total: 1, conceded: 0, assists: null, saves: null },
        passes: { total: 108, key: 4, accuracy: 30 },
        tackles: { total: 5, blocks: null, interceptions: 3 },
        duels: { total: 24, won: 16 },
        dribbles: { attempts: 2, success: 1, past: null },
        fouls: { drawn: 7, committed: 1 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 5,
          lineups: 1,
          minutes: 178,
          number: null,
          position: "Midfielder",
          rating: "6.840000",
          captain: false,
        },
        substitutes: { in: 4, out: 1, bench: 4 },
        shots: { total: 3, on: null },
        goals: { total: 1, conceded: 0, assists: 2, saves: null },
        passes: { total: 107, key: 5, accuracy: 17 },
        tackles: { total: 3, blocks: null, interceptions: 3 },
        duels: { total: 39, won: 20 },
        dribbles: { attempts: 7, success: 4, past: null },
        fouls: { drawn: 8, committed: 2 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 3,
          name: "UEFA Europa League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/3.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 2,
          minutes: 164,
          number: null,
          position: "Midfielder",
          rating: "7.433333",
          captain: false,
        },
        substitutes: { in: 1, out: 2, bench: 1 },
        shots: { total: 4, on: 1 },
        goals: { total: 1, conceded: 0, assists: 1, saves: null },
        passes: { total: 115, key: 6, accuracy: 31 },
        tackles: { total: 7, blocks: null, interceptions: 2 },
        duels: { total: 36, won: 21 },
        dribbles: { attempts: 7, success: 5, past: null },
        fouls: { drawn: 3, committed: 6 },
        cards: { yellow: 2, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 33,
        name: "Manchester United",
        logo: "https://media.api-sports.io/football/teams/33.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 36,
        lineups: 25,
        minutes: 2323,
        number: null,
        position: "Midfielder",
        rating: "7.3236681376",
        captain: false,
      },
      substitutes: { in: 11, out: 8, bench: 13 },
      shots: { total: 35, on: 15 },
      goals: { total: 6, conceded: 0, assists: 6, saves: null },
      passes: { total: 1594, key: 34, accuracy: 154 },
      tackles: { total: 47, blocks: 3, interceptions: 34 },
      duels: { total: 403, won: 217 },
      dribbles: { attempts: 74, success: 52, past: null },
      fouls: { drawn: 54, committed: 43 },
      cards: { yellow: 7, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 0, missed: 0, saved: null },
    },
    votes: 0,
  },
  {
    id: 909,
    personalInfo: {
      name: "M. Rashford",
      firstname: "Marcus",
      lastname: "Rashford",
      age: 24,
      nationality: "England",
      height: "180 cm",
      weight: "70 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/909.png",
    },
    statistics: [
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 33,
          lineups: 31,
          minutes: 2695,
          number: null,
          position: "Attacker",
          rating: "6.906060",
          captain: false,
        },
        substitutes: { in: 2, out: 11, bench: 2 },
        shots: { total: 53, on: 35 },
        goals: { total: 10, conceded: 0, assists: 8, saves: null },
        passes: { total: 1108, key: 37, accuracy: 27 },
        tackles: { total: 15, blocks: 2, interceptions: 8 },
        duels: { total: 333, won: 152 },
        dribbles: { attempts: 153, success: 80, past: null },
        fouls: { drawn: 37, committed: 23 },
        cards: { yellow: 4, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 4,
          lineups: 1,
          minutes: 145,
          number: null,
          position: "Attacker",
          rating: "6.975000",
          captain: false,
        },
        substitutes: { in: 3, out: 0, bench: 3 },
        shots: { total: 3, on: 3 },
        goals: { total: 1, conceded: 0, assists: 1, saves: null },
        passes: { total: 44, key: 3, accuracy: 8 },
        tackles: { total: 1, blocks: null, interceptions: 1 },
        duels: { total: 20, won: 9 },
        dribbles: { attempts: 4, success: 3, past: null },
        fouls: { drawn: 2, committed: 2 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 2,
          minutes: 227,
          number: null,
          position: "Attacker",
          rating: "7.100000",
          captain: false,
        },
        substitutes: { in: 1, out: 1, bench: 1 },
        shots: { total: 4, on: 4 },
        goals: { total: 1, conceded: 0, assists: 2, saves: null },
        passes: { total: 89, key: 4, accuracy: 24 },
        tackles: { total: 1, blocks: null, interceptions: 1 },
        duels: { total: 33, won: 17 },
        dribbles: { attempts: 18, success: 9, past: null },
        fouls: { drawn: 5, committed: 2 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 6,
          lineups: 5,
          minutes: 416,
          number: null,
          position: "Attacker",
          rating: "7.450000",
          captain: false,
        },
        substitutes: { in: 1, out: 3, bench: 1 },
        shots: { total: 14, on: 12 },
        goals: { total: 6, conceded: 0, assists: null, saves: null },
        passes: { total: 140, key: 5, accuracy: 18 },
        tackles: { total: 1, blocks: null, interceptions: null },
        duels: { total: 54, won: 24 },
        dribbles: { attempts: 28, success: 15, past: null },
        fouls: { drawn: 8, committed: 1 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 1,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 3,
          name: "UEFA Europa League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/3.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 4,
          lineups: 3,
          minutes: 224,
          number: null,
          position: "Attacker",
          rating: "7.050000",
          captain: false,
        },
        substitutes: { in: 1, out: 3, bench: 2 },
        shots: { total: 7, on: 4 },
        goals: { total: 2, conceded: 0, assists: null, saves: null },
        passes: { total: 75, key: 3, accuracy: 15 },
        tackles: { total: 1, blocks: null, interceptions: null },
        duels: { total: 29, won: 14 },
        dribbles: { attempts: 12, success: 9, past: null },
        fouls: { drawn: 4, committed: 2 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 33,
        name: "Manchester United",
        logo: "https://media.api-sports.io/football/teams/33.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 51,
        lineups: 43,
        minutes: 3782,
        number: null,
        position: "Attacker",
        rating: "1.184385424382716",
        captain: false,
      },
      substitutes: { in: 8, out: 19, bench: 9 },
      shots: { total: 81, on: 58 },
      goals: { total: 20, conceded: null, assists: 11, saves: null },
      passes: { total: 1456, key: 52, accuracy: 92 },
      tackles: { total: 19, blocks: 2, interceptions: 10 },
      duels: { total: 469, won: 216 },
      dribbles: { attempts: 215, success: 116, past: null },
      fouls: { drawn: 56, committed: 30 },
      cards: { yellow: 4, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: 1,
        missed: null,
        saved: null,
      },
    },
    votes: 0,
  },
  {
    id: 1485,
    personalInfo: {
      name: "Bruno Fernandes",
      firstname: "Bruno Miguel",
      lastname: "Borges Fernandes",
      age: 27,
      nationality: "Portugal",
      height: "179 cm",
      weight: "80 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/1485.png",
    },
    statistics: [
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 33,
          lineups: 32,
          minutes: 2831,
          number: null,
          position: "Midfielder",
          rating: "7.600000",
          captain: false,
        },
        substitutes: { in: 1, out: 11, bench: 1 },
        shots: { total: 70, on: 45 },
        goals: { total: 16, conceded: 0, assists: 11, saves: null },
        passes: { total: 1915, key: 91, accuracy: 45 },
        tackles: { total: 53, blocks: null, interceptions: 24 },
        duels: { total: 326, won: 130 },
        dribbles: { attempts: 38, success: 18, past: null },
        fouls: { drawn: 46, committed: 38 },
        cards: { yellow: 5, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 8,
          missed: 1,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 2,
          minutes: 192,
          number: null,
          position: "Midfielder",
          rating: "7.300000",
          captain: false,
        },
        substitutes: { in: 1, out: 0, bench: 1 },
        shots: { total: 8, on: 4 },
        goals: { total: 0, conceded: 0, assists: 1, saves: null },
        passes: { total: 122, key: 3, accuracy: 30 },
        tackles: { total: 5, blocks: null, interceptions: null },
        duels: { total: 14, won: 7 },
        dribbles: { attempts: 2, success: 1, past: null },
        fouls: { drawn: 1, committed: 3 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 3,
          lineups: 0,
          minutes: 97,
          number: null,
          position: "Midfielder",
          rating: "7.100000",
          captain: false,
        },
        substitutes: { in: 3, out: 0, bench: 4 },
        shots: { total: 2, on: 2 },
        goals: { total: 1, conceded: 0, assists: null, saves: null },
        passes: { total: 79, key: 1, accuracy: 20 },
        tackles: { total: 3, blocks: null, interceptions: 1 },
        duels: { total: 12, won: 6 },
        dribbles: { attempts: 1, success: 1, past: null },
        fouls: { drawn: 1, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 6,
          lineups: 5,
          minutes: 439,
          number: null,
          position: "Midfielder",
          rating: "7.883333",
          captain: false,
        },
        substitutes: { in: 1, out: 2, bench: 1 },
        shots: { total: 17, on: 9 },
        goals: { total: 4, conceded: 0, assists: 1, saves: null },
        passes: { total: 292, key: 14, accuracy: 35 },
        tackles: { total: 9, blocks: null, interceptions: 4 },
        duels: { total: 54, won: 23 },
        dribbles: { attempts: 7, success: 3, past: null },
        fouls: { drawn: 9, committed: 4 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 2,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 33,
          name: "Manchester United",
          logo: "https://media.api-sports.io/football/teams/33.png",
        },
        league: {
          id: 3,
          name: "UEFA Europa League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/3.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 6,
          lineups: 6,
          minutes: 456,
          number: null,
          position: "Midfielder",
          rating: "7.516666",
          captain: false,
        },
        substitutes: { in: 0, out: 4, bench: 0 },
        shots: { total: 11, on: 7 },
        goals: { total: 3, conceded: 0, assists: 1, saves: null },
        passes: { total: 288, key: 14, accuracy: 38 },
        tackles: { total: 10, blocks: null, interceptions: 3 },
        duels: { total: 58, won: 28 },
        dribbles: { attempts: 7, success: 4, past: null },
        fouls: { drawn: 10, committed: 3 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 1,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 33,
        name: "Manchester United",
        logo: "https://media.api-sports.io/football/teams/33.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 51,
        lineups: 45,
        minutes: 4015,
        number: null,
        position: "Midfielder",
        rating: "7.5607460799999995",
        captain: false,
      },
      substitutes: { in: 6, out: 17, bench: 7 },
      shots: { total: 108, on: 67 },
      goals: { total: 24, conceded: 0, assists: 14, saves: null },
      passes: { total: 2696, key: 123, accuracy: 168 },
      tackles: { total: 80, blocks: null, interceptions: 32 },
      duels: { total: 464, won: 194 },
      dribbles: { attempts: 55, success: 27, past: null },
      fouls: { drawn: 67, committed: 48 },
      cards: { yellow: 6, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: 11,
        missed: 1,
        saved: null,
      },
    },
    votes: 0,
  },
  {
    id: 290,
    personalInfo: {
      name: "V. van Dijk",
      firstname: "Virgil",
      lastname: "van Dijk",
      age: 30,
      nationality: "Netherlands",
      height: "193 cm",
      weight: "92 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/290.png",
    },
    statistics: [
      {
        team: {
          id: 40,
          name: "Liverpool",
          logo: "https://media.api-sports.io/football/teams/40.png",
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/39.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 5,
          lineups: 5,
          minutes: 371,
          number: null,
          position: "Defender",
          rating: "6.680000",
          captain: false,
        },
        substitutes: { in: 0, out: 1, bench: 0 },
        shots: { total: 3, on: 2 },
        goals: { total: 1, conceded: 0, assists: null, saves: null },
        passes: { total: 341, key: null, accuracy: 61 },
        tackles: { total: 3, blocks: 1, interceptions: 5 },
        duels: { total: 27, won: 17 },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: 2, committed: 4 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 40,
          name: "Liverpool",
          logo: "https://media.api-sports.io/football/teams/40.png",
        },
        league: {
          id: 48,
          name: "League Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/48.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 2,
          lineups: 2,
          minutes: 107,
          number: null,
          position: "Defender",
          rating: "7.100000",
          captain: false,
        },
        substitutes: { in: 0, out: 2, bench: 0 },
        shots: { total: 1, on: 1 },
        goals: { total: 0, conceded: 0, assists: null, saves: null },
        passes: { total: 105, key: 1, accuracy: 46 },
        tackles: { total: 1, blocks: null, interceptions: null },
        duels: { total: 5, won: 4 },
        dribbles: { attempts: 1, success: 1, past: null },
        fouls: { drawn: null, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 40,
          name: "Liverpool",
          logo: "https://media.api-sports.io/football/teams/40.png",
        },
        league: {
          id: 45,
          name: "FA Cup",
          country: "England",
          logo: "https://media.api-sports.io/football/leagues/45.png",
          flag: "https://media.api-sports.io/flags/gb.svg",
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: "Defender",
          rating: null,
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: null, assists: null, saves: null },
        passes: { total: null, key: null, accuracy: null },
        tackles: { total: null, blocks: null, interceptions: null },
        duels: { total: null, won: null },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: null, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: null,
          missed: null,
          saved: null,
        },
      },
      {
        team: {
          id: 40,
          name: "Liverpool",
          logo: "https://media.api-sports.io/football/teams/40.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 0,
          lineups: 0,
          minutes: 0,
          number: null,
          position: "Defender",
          rating: null,
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: null, assists: null, saves: null },
        passes: { total: null, key: null, accuracy: null },
        tackles: { total: null, blocks: null, interceptions: null },
        duels: { total: null, won: null },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: null, committed: null },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: null,
          missed: null,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 40,
        name: "Liverpool",
        logo: "https://media.api-sports.io/football/teams/40.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb.svg",
        season: 2020,
      },
      games: {
        appearences: 9,
        lineups: 9,
        minutes: 580,
        number: null,
        position: "Defender",
        rating: "0.056128",
        captain: false,
      },
      substitutes: { in: 0, out: 5, bench: 0 },
      shots: { total: 4, on: 3 },
      goals: { total: 1, conceded: null, assists: null, saves: null },
      passes: { total: 446, key: 1, accuracy: 107 },
      tackles: { total: 4, blocks: 1, interceptions: 5 },
      duels: { total: 32, won: 21 },
      dribbles: { attempts: 1, success: 1, past: null },
      fouls: { drawn: 2, committed: 4 },
      cards: { yellow: 1, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: null,
        missed: null,
        saved: null,
      },
    },
    votes: 0,
  },
  {
    id: 162712,
    personalInfo: {
      name: "Óscar Mingueza",
      firstname: "Óscar",
      lastname: "Mingueza García",
      age: 22,
      nationality: "Spain",
      height: "184 cm",
      weight: "75 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/162712.png",
    },
    statistics: [
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 140,
          name: "Primera Division",
          country: "Spain",
          logo: "https://media.api-sports.io/football/leagues/140.png",
          flag: "https://media.api-sports.io/flags/es.svg",
          season: 2020,
        },
        games: {
          appearences: 23,
          lineups: 20,
          minutes: 1725,
          number: null,
          position: "Defender",
          rating: "7.021739",
          captain: false,
        },
        substitutes: { in: 3, out: 5, bench: 7 },
        shots: { total: 10, on: 5 },
        goals: { total: 2, conceded: 0, assists: 2, saves: null },
        passes: { total: 1408, key: 8, accuracy: 56 },
        tackles: { total: 49, blocks: 4, interceptions: 18 },
        duels: { total: 146, won: 85 },
        dribbles: { attempts: 10, success: 8, past: null },
        fouls: { drawn: 15, committed: 18 },
        cards: { yellow: 4, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 143,
          name: "Copa del Rey",
          country: "Spain",
          logo: "https://media.api-sports.io/football/leagues/143.png",
          flag: "https://media.api-sports.io/flags/es.svg",
          season: 2020,
        },
        games: {
          appearences: 5,
          lineups: 5,
          minutes: 465,
          number: null,
          position: "Defender",
          rating: "7.040000",
          captain: false,
        },
        substitutes: { in: 0, out: 2, bench: 1 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 0, assists: null, saves: null },
        passes: { total: 386, key: 1, accuracy: 71 },
        tackles: { total: 10, blocks: 3, interceptions: 8 },
        duels: { total: 38, won: 21 },
        dribbles: { attempts: 1, success: 1, past: null },
        fouls: { drawn: 6, committed: 11 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 5,
          lineups: 3,
          minutes: 242,
          number: null,
          position: "Defender",
          rating: "6.920000",
          captain: false,
        },
        substitutes: { in: 2, out: 1, bench: 3 },
        shots: { total: 1, on: null },
        goals: { total: 0, conceded: 0, assists: 1, saves: null },
        passes: { total: 224, key: 1, accuracy: 41 },
        tackles: { total: 6, blocks: 2, interceptions: 10 },
        duels: { total: 22, won: 9 },
        dribbles: { attempts: null, success: null, past: null },
        fouls: { drawn: null, committed: 9 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 529,
        name: "Barcelona",
        logo: "https://media.api-sports.io/football/teams/529.png",
      },
      league: {
        id: 140,
        name: "Primera Division",
        country: "Spain",
        logo: "https://media.api-sports.io/football/leagues/140.png",
        flag: "https://media.api-sports.io/flags/es.svg",
        season: 2020,
      },
      games: {
        appearences: 33,
        lineups: 28,
        minutes: 2432,
        number: null,
        position: "Defender",
        rating: "1.737214671875",
        captain: false,
      },
      substitutes: { in: 5, out: 8, bench: 11 },
      shots: { total: 11, on: 5 },
      goals: { total: 2, conceded: null, assists: 3, saves: null },
      passes: { total: 2018, key: 10, accuracy: 168 },
      tackles: { total: 65, blocks: 9, interceptions: 36 },
      duels: { total: 206, won: 115 },
      dribbles: { attempts: 11, success: 9, past: null },
      fouls: { drawn: 21, committed: 38 },
      cards: { yellow: 6, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: null,
        missed: null,
        saved: null,
      },
    },
    votes: 0,
  },
  {
    id: 154,
    personalInfo: {
      name: "L. Messi",
      firstname: "Lionel Andrés",
      lastname: "Messi Cuccittini",
      age: 34,
      nationality: "Argentina",
      height: "170 cm",
      weight: "72 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/154.png",
    },
    statistics: [
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 140,
          name: "Primera Division",
          country: "Spain",
          logo: "https://media.api-sports.io/football/leagues/140.png",
          flag: "https://media.api-sports.io/flags/es.svg",
          season: 2020,
        },
        games: {
          appearences: 30,
          lineups: 28,
          minutes: 2572,
          number: null,
          position: "Attacker",
          rating: "8.296666",
          captain: false,
        },
        substitutes: { in: 2, out: 1, bench: 2 },
        shots: { total: 123, on: 81 },
        goals: { total: 25, conceded: 0, assists: 9, saves: null },
        passes: { total: 1917, key: 70, accuracy: 54 },
        tackles: { total: 15, blocks: null, interceptions: 5 },
        duels: { total: 417, won: 227 },
        dribbles: { attempts: 203, success: 127, past: null },
        fouls: { drawn: 77, committed: 21 },
        cards: { yellow: 4, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 3,
          missed: 1,
          saved: null,
        },
      },
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 143,
          name: "Copa del Rey",
          country: "Spain",
          logo: "https://media.api-sports.io/football/leagues/143.png",
          flag: "https://media.api-sports.io/flags/es.svg",
          season: 2020,
        },
        games: {
          appearences: 5,
          lineups: 5,
          minutes: 510,
          number: null,
          position: "Attacker",
          rating: "8.740000",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: 22, on: 17 },
        goals: { total: 3, conceded: 0, assists: 1, saves: null },
        passes: { total: 366, key: 18, accuracy: 61 },
        tackles: { total: 4, blocks: null, interceptions: 1 },
        duels: { total: 90, won: 60 },
        dribbles: { attempts: 43, success: 35, past: null },
        fouls: { drawn: 21, committed: 3 },
        cards: { yellow: 2, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 6,
          lineups: 6,
          minutes: 540,
          number: null,
          position: "Attacker",
          rating: "8.283333",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: 26, on: 20 },
        goals: { total: 5, conceded: 0, assists: 2, saves: null },
        passes: { total: 433, key: 23, accuracy: 64 },
        tackles: { total: 5, blocks: null, interceptions: 2 },
        duels: { total: 94, won: 45 },
        dribbles: { attempts: 44, success: 28, past: null },
        fouls: { drawn: 12, committed: 2 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 4,
          missed: 1,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 529,
        name: "Barcelona",
        logo: "https://media.api-sports.io/football/teams/529.png",
      },
      league: {
        id: 140,
        name: "Primera Division",
        country: "Spain",
        logo: "https://media.api-sports.io/football/leagues/140.png",
        flag: "https://media.api-sports.io/flags/es.svg",
        season: 2020,
      },
      games: {
        appearences: 43,
        lineups: 41,
        minutes: 3731,
        number: null,
        position: "Attacker",
        rating: "2.09244784375",
        captain: false,
      },
      substitutes: { in: 2, out: 3, bench: 2 },
      shots: { total: 171, on: 118 },
      goals: { total: 35, conceded: null, assists: 12, saves: null },
      passes: { total: 2716, key: 111, accuracy: 179 },
      tackles: { total: 24, blocks: null, interceptions: 8 },
      duels: { total: 601, won: 332 },
      dribbles: { attempts: 290, success: 190, past: null },
      fouls: { drawn: 110, committed: 26 },
      cards: { yellow: 6, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 7, missed: 2, saved: null },
    },
    votes: 0,
  },
  {
    id: 538,
    personalInfo: {
      name: "F. de Jong",
      firstname: "Frenkie",
      lastname: "de Jong",
      age: 24,
      nationality: "Netherlands",
      height: "180 cm",
      weight: "74 kg",
      injured: false,
      photo: "https://media.api-sports.io/football/players/538.png",
    },
    statistics: [
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 140,
          name: "Primera Division",
          country: "Spain",
          logo: "https://media.api-sports.io/football/leagues/140.png",
          flag: "https://media.api-sports.io/flags/es.svg",
          season: 2020,
        },
        games: {
          appearences: 32,
          lineups: 30,
          minutes: 2724,
          number: null,
          position: "Midfielder",
          rating: "7.206250",
          captain: false,
        },
        substitutes: { in: 2, out: 5, bench: 2 },
        shots: { total: 11, on: 5 },
        goals: { total: 3, conceded: 0, assists: 4, saves: null },
        passes: { total: 2453, key: 37, accuracy: 70 },
        tackles: { total: 39, blocks: 4, interceptions: 30 },
        duels: { total: 254, won: 166 },
        dribbles: { attempts: 61, success: 53, past: null },
        fouls: { drawn: 38, committed: 20 },
        cards: { yellow: 4, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 143,
          name: "Copa del Rey",
          country: "Spain",
          logo: "https://media.api-sports.io/football/leagues/143.png",
          flag: "https://media.api-sports.io/flags/es.svg",
          season: 2020,
        },
        games: {
          appearences: 5,
          lineups: 5,
          minutes: 510,
          number: null,
          position: "Midfielder",
          rating: "7.620000",
          captain: false,
        },
        substitutes: { in: 0, out: 0, bench: 0 },
        shots: { total: 5, on: 3 },
        goals: { total: 3, conceded: 0, assists: 2, saves: null },
        passes: { total: 376, key: 8, accuracy: 69 },
        tackles: { total: 7, blocks: 2, interceptions: 4 },
        duels: { total: 46, won: 28 },
        dribbles: { attempts: 10, success: 9, past: null },
        fouls: { drawn: 10, committed: 4 },
        cards: { yellow: 0, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
      {
        team: {
          id: 529,
          name: "Barcelona",
          logo: "https://media.api-sports.io/football/teams/529.png",
        },
        league: {
          id: 2,
          name: "UEFA Champions League",
          country: "World",
          logo: "https://media.api-sports.io/football/leagues/2.png",
          flag: null,
          season: 2020,
        },
        games: {
          appearences: 7,
          lineups: 6,
          minutes: 584,
          number: null,
          position: "Midfielder",
          rating: "7.014285",
          captain: false,
        },
        substitutes: { in: 1, out: 0, bench: 1 },
        shots: { total: null, on: null },
        goals: { total: 0, conceded: 0, assists: 1, saves: null },
        passes: { total: 506, key: 4, accuracy: 68 },
        tackles: { total: 8, blocks: 1, interceptions: 15 },
        duels: { total: 39, won: 26 },
        dribbles: { attempts: 5, success: 4, past: null },
        fouls: { drawn: 7, committed: 1 },
        cards: { yellow: 1, yellowred: 0, red: 0 },
        penalty: {
          won: null,
          commited: null,
          scored: 0,
          missed: 0,
          saved: null,
        },
      },
    ],
    total: {
      team: {
        id: 529,
        name: "Barcelona",
        logo: "https://media.api-sports.io/football/teams/529.png",
      },
      league: {
        id: 140,
        name: "Primera Division",
        country: "Spain",
        logo: "https://media.api-sports.io/football/leagues/140.png",
        flag: "https://media.api-sports.io/flags/es.svg",
        season: 2020,
      },
      games: {
        appearences: 46,
        lineups: 42,
        minutes: 3925,
        number: null,
        position: "Midfielder",
        rating: "1.7849635937500001",
        captain: false,
      },
      substitutes: { in: 4, out: 6, bench: 4 },
      shots: { total: 16, on: 8 },
      goals: { total: 6, conceded: null, assists: 7, saves: null },
      passes: { total: 3335, key: 49, accuracy: 207 },
      tackles: { total: 54, blocks: 7, interceptions: 49 },
      duels: { total: 339, won: 220 },
      dribbles: { attempts: 76, success: 66, past: null },
      fouls: { drawn: 55, committed: 25 },
      cards: { yellow: 5, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: null,
        missed: null,
        saved: null,
      },
    },
    votes: 0,
  },
];
