version: "3"

services:
  mongodb:
    image: mongo:4.4-bionic
    container_name: football_mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - football_mongodb_data_container:/data/db
      - ./docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

volumes:
  football_mongodb_data_container:
